server:
  port: 8001 #\u7A0B\u5E8F\u542F\u52A8\u7AEF\u53E3,tomcat\u7AEF\u53E3(\u53EF\u81EA\u5B9A\u4E49)
spring:
  application:
    name: dream-zuul #\u5E94\u7528\u540D\u79F0(\u522B\u540D)

eureka:
  instance:
    non-secure-port: ${server.port:9001}
    preferIpAddress: true
    metadata-map:
       instanceId: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.defaultZone:http://localhost:8761/eureka/}

zuul:
  routes:
    hello-service:
      path: /getAccount
      serviceId: dream-customer