spring:
  application:
    name: dream-admin
  profiles:
    active: ${config.profile:dev}
  cloud:
    config:
      uri: ${spring.cloud.url:http://127.0.0.1:8888}
      name: dream-admin
      profile: ${config.profile:dev}

    loadbalancer:
      retry:
        enabled: false

  thymeleaf:
    prefix: classpath:/views
    suffix: .html
    cache: false


server:
  port: 9002
  tomcat:
    uri-encoding: UTF-8

eureka:
  instance:
    non-secure-port: ${server.port:9001}
    preferIpAddress: true
    metadata-map:
       instanceId: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.defaultZone:http://localhost:8761/eureka/}