spring:
  application:
    name: dream-admin
  profiles:
    active: ${config.profile:dev}
  cloud:
    config:
      uri: ${spring.cloud.url:http://127.0.0.1:8888}
      name: dream-admin
      profile: ${config.profile:dev}
    alibaba:
      fescar:
        tx-service-group: my_test_tx_group
    loadbalancer:
      retry:
        enabled: false
   

  thymeleaf:
    prefix: classpath:/views
    suffix: .html
    cache: false
  datasource:                          
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20   
    maxWait: 60000  
    filters: stat
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
mybatis:
  typeAliasesPackage: com.lenily.dreamadmin.entity
  mapperLocations: classpath:com/lenily/dreamadmin/mapper/*.xml
server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8

eureka:
  instance:
    non-secure-port: ${server.port:9001}
    preferIpAddress: true
    metadata-map:
       instanceId: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.defaultZone:http://localhost:8761/eureka/}
logging:
  level:
   org:
     springframework:
       cloud:
         alibaba:
           fescar:
             web: debug
   com:
     alibaba:
       fescar: debug