spring:
  application:
    name: dream-customer
  profiles:
    active: ${config.profile:dev}
  cloud:
    config:
      uri: ${spring.cloud.url:http://127.0.0.1:8888}
      name: dream-customer
      profile: ${config.profile:dev}

    loadbalancer:
      retry:
        enabled: false

  thymeleaf:
    prefix: classpath:/views
    suffix: .html
    cache: false
  datasource:                          
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20   
    maxWait: 60000  
    filters: stat
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
mybatis:
  typeAliasesPackage: com.lenily.dreamcustomer.entity
  mapperLocations: classpath:com/lenily/dreamcustomer/mapper/*.xml
server:
  port: 9002
  tomcat:
    uri-encoding: UTF-8

eureka:
  instance:
    non-secure-port: ${server.port:9002}
    preferIpAddress: true
    metadata-map:
       instanceId: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.defaultZone:http://localhost:8761/eureka/}